version: '3.8'

services:
  # 1. MySQL 数据库服务
  mysql:
    image: mysql:8.0
    container_name: elm-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root # 使用你自己的密码
      MYSQL_DATABASE: elm_user # 可以先创建一个默认库，其他库由SQL脚本创建
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      # 挂载数据卷，实现数据持久化
      - mysql-data:/var/lib/mysql
      # 挂载SQL初始化脚本，容器启动时会自动执行
      - ./creatDataBase.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - elm-network

  # 2. Nacos 服务
  nacos:
    image: nacos/nacos-server:v2.2.3 # 建议使用与你本地版本相近的镜像
    container_name: elm-nacos
    restart: always
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone # 单机模式
      - NACOS_AUTH_ENABLE=false # 禁用Nacos登录认证，方便调试
      - TZ=Asia/Shanghai
    ports:
      - "8848:8848" # Nacos 服务端口
      - "9848:9848" # Nacos 集群通信端口
    depends_on:
      - mysql # 确保在MySQL启动后再启动
    networks:
      - elm-network

  # 3. Sentinel 服务
  sentinel:
    image: bladex/sentinel-dashboard # 这是一个常用的Sentinel Dashboard镜像
    container_name: elm-sentinel
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "8858:8858" # Sentinel Dashboard 端口
    networks:
      - elm-network

  # 4. 用户服务
  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: elm-user-service
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - nacos
    networks:
      - elm-network

  # 5. 商家服务
  store-service:
    build:
      context: ./services/store-service
      dockerfile: Dockerfile
    container_name: elm-store-service
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - nacos
    networks:
      - elm-network

  # 6. 订单服务
  order-service:
    build:
      context: ./services/order-service
      dockerfile: Dockerfile
    container_name: elm-order-service
    restart: always
    ports:
      - "8083:8083"
    depends_on:
      - nacos
    networks:
      - elm-network

  # 7. 支付服务
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: elm-payment-service
    restart: always
    ports:
      - "8084:8084"
    depends_on:
      - nacos
    networks:
      - elm-network

  # 8. 网关服务
  gateway-service:
    build:
      context: ./services/gateway-service
      dockerfile: Dockerfile
    container_name: elm-gateway-service
    restart: always
    ports:
      - "8080:8080" # 网关是外部访问入口，必须暴露端口
    depends_on:
      - nacos
      - user-service
      - store-service
      - order-service
      - payment-service
    networks:
      - elm-network

# 定义网络
networks:
  elm-network:
    driver: bridge

# 定义数据卷
volumes:
  mysql-data: