server:
  port: 8082
  
spring:
  application:
    name: store-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/elm_store?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: nacos:8848
        namespace: public
        group: DEFAULT_GROUP
      config:
        server-addr: nacos:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yml
    sentinel:
      transport:
        dashboard: sentinel:8858
      enabled: false  # 禁用 Sentinel

mybatis:
  # mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: ynu.edu.storeservice.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    ynu.edu: debug
